/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_tag = 1,
  aux_sym__empty_line_token1 = 2,
  anon_sym_PERCENT = 3,
  anon_sym_COMMA = 4,
  sym_desc_line = 5,
  sym_text_block = 6,
  sym_note = 7,
  sym_note_block = 8,
  sym__empty_line = 9,
  sym_tag_line = 10,
  aux_sym_note_repeat1 = 11,
  aux_sym_note_block_repeat1 = 12,
  aux_sym_tag_line_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_tag] = "tag",
  [aux_sym__empty_line_token1] = "_empty_line_token1",
  [anon_sym_PERCENT] = "%",
  [anon_sym_COMMA] = ",",
  [sym_desc_line] = "desc_line",
  [sym_text_block] = "text_block",
  [sym_note] = "note",
  [sym_note_block] = "note_block",
  [sym__empty_line] = "_empty_line",
  [sym_tag_line] = "tag_line",
  [aux_sym_note_repeat1] = "note_repeat1",
  [aux_sym_note_block_repeat1] = "note_block_repeat1",
  [aux_sym_tag_line_repeat1] = "tag_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_tag] = sym_tag,
  [aux_sym__empty_line_token1] = aux_sym__empty_line_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_desc_line] = sym_desc_line,
  [sym_text_block] = sym_text_block,
  [sym_note] = sym_note,
  [sym_note_block] = sym_note_block,
  [sym__empty_line] = sym__empty_line,
  [sym_tag_line] = sym_tag_line,
  [aux_sym_note_repeat1] = aux_sym_note_repeat1,
  [aux_sym_note_block_repeat1] = aux_sym_note_block_repeat1,
  [aux_sym_tag_line_repeat1] = aux_sym_tag_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__empty_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_desc_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_block] = {
    .visible = true,
    .named = true,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [sym_note_block] = {
    .visible = true,
    .named = true,
  },
  [sym__empty_line] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_note_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_note_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '%') ADVANCE(9);
      if (lookahead == ',') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '%') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '%') ADVANCE(9);
      if (lookahead == ',') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '%') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym__empty_line_token1);
      if (lookahead == '\n') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__empty_line_token1);
      if (lookahead == '\n') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_desc_line);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text_block);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_desc_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_note] = STATE(14),
    [sym_note_block] = STATE(2),
    [sym__empty_line] = STATE(2),
    [sym_tag_line] = STATE(4),
    [aux_sym_note_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__empty_line_token1] = ACTIONS(5),
    [anon_sym_PERCENT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      anon_sym_PERCENT,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      aux_sym__empty_line_token1,
    STATE(4), 1,
      sym_tag_line,
    STATE(3), 3,
      sym_note_block,
      sym__empty_line,
      aux_sym_note_repeat1,
  [18] = 5,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      aux_sym__empty_line_token1,
    ACTIONS(18), 1,
      anon_sym_PERCENT,
    STATE(4), 1,
      sym_tag_line,
    STATE(3), 3,
      sym_note_block,
      sym__empty_line,
      aux_sym_note_repeat1,
  [36] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      aux_sym_note_block_repeat1,
    ACTIONS(23), 2,
      aux_sym__empty_line_token1,
      anon_sym_PERCENT,
    ACTIONS(25), 2,
      sym_desc_line,
      sym_text_block,
  [51] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_note_block_repeat1,
    ACTIONS(29), 2,
      aux_sym__empty_line_token1,
      anon_sym_PERCENT,
    ACTIONS(31), 2,
      sym_desc_line,
      sym_text_block,
  [66] = 4,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_note_block_repeat1,
    ACTIONS(35), 2,
      aux_sym__empty_line_token1,
      anon_sym_PERCENT,
    ACTIONS(37), 2,
      sym_desc_line,
      sym_text_block,
  [81] = 2,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 4,
      aux_sym__empty_line_token1,
      anon_sym_PERCENT,
      sym_desc_line,
      sym_text_block,
  [91] = 2,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 4,
      aux_sym__empty_line_token1,
      anon_sym_PERCENT,
      sym_desc_line,
      sym_text_block,
  [101] = 3,
    ACTIONS(48), 1,
      aux_sym__empty_line_token1,
    ACTIONS(50), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym_tag_line_repeat1,
  [111] = 3,
    ACTIONS(50), 1,
      anon_sym_COMMA,
    ACTIONS(52), 1,
      aux_sym__empty_line_token1,
    STATE(11), 1,
      aux_sym_tag_line_repeat1,
  [121] = 3,
    ACTIONS(54), 1,
      aux_sym__empty_line_token1,
    ACTIONS(56), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_tag_line_repeat1,
  [131] = 2,
    ACTIONS(54), 1,
      aux_sym__empty_line_token1,
    ACTIONS(59), 1,
      anon_sym_COMMA,
  [138] = 1,
    ACTIONS(61), 1,
      sym_tag,
  [142] = 1,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
  [146] = 1,
    ACTIONS(65), 1,
      sym_tag,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 36,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 66,
  [SMALL_STATE(7)] = 81,
  [SMALL_STATE(8)] = 91,
  [SMALL_STATE(9)] = 101,
  [SMALL_STATE(10)] = 111,
  [SMALL_STATE(11)] = 121,
  [SMALL_STATE(12)] = 131,
  [SMALL_STATE(13)] = 138,
  [SMALL_STATE(14)] = 142,
  [SMALL_STATE(15)] = 146,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_note_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_note_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_block, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_block, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_note_block, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_note_block, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_note_block_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_note_block_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_note_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_line, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_line, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_line, 4, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_line, 4, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [63] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_llnotes(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_tag,
    .primary_state_ids = ts_primary_state_ids,
    .name = "llnotes",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
